# Generated by Django 4.1.6 on 2023-02-18 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exhauster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serviceability", models.BooleanField(default=True)),
                ("last_replacement_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("measure", models.CharField(default="", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="SinterMachine",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="SystemIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measurement_time", models.DateTimeField()),
                ("value", models.FloatField()),
                (
                    "exhauster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_loader.exhauster",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_loader.metric",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exhauster",
            name="sinter_machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="data_loader.sintermachine",
            ),
        ),
    ]
