# Generated by Django 4.1.6 on 2023-02-18 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("measure", models.CharField(default="", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="SinterMachine",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Exhauster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serviceability", models.BooleanField(default=True)),
                ("last_replacement_date", models.DateField()),
                (
                    "sinter_machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_loader.sintermachine",
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql=[
                (
                    "CREATE TABLE public.data_loader_systemindicator ("
                    "measurement_time timestamp with time zone not null,"
                    "value            double precision,"
                    "exhauster_id     bigint                   not null"
                    "    constraint data_loader_systemin_exhauster_id_edfe6e49_fk_data_load"
                    "        references data_loader_exhauster"
                    "        deferrable initially deferred,"
                    "metric_id        bigint                   not null"
                    "    constraint data_loader_systemin_metric_id_afbcec40_fk_data_load"
                    "        references data_loader_metric"
                    "        deferrable initially deferred,"
                    "constraint systemindicator_pkey PRIMARY KEY (exhauster_id, metric_id, measurement_time)"
                    ");"
                    "SELECT create_hypertable("
                    "   'data_loader_systemindicator', 'measurement_time', chunk_time_interval => INTERVAL '5 days'"
                    ");"
                    "CREATE INDEX ON data_loader_systemindicator (measurement_time DESC, metric_id);"
                    "CREATE INDEX ON data_loader_systemindicator (measurement_time DESC);"
                    ""
                )
            ],
            reverse_sql=["DROP TABLE public.data_loader_systemindicator;"],
        ),
        migrations.CreateModel(
            name="SystemIndicator",
            fields=[
                (
                    "measurement_time",
                    models.DateTimeField(primary_key=True, serialize=False),
                ),
                ("value", models.FloatField()),
            ],
            options={
                "db_table": "data_loader_systemindicator",
                "managed": False,
            },
        ),
    ]
