# Generated by Django 4.1.6 on 2023-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_loader", "0002_alter_metric_measure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhauster",
            name="last_replacement_date",
            field=models.DateField(),
        ),
    ]
